Update README.rst
I followed the tutorial and it was great, but I had the error below
 ```TypeError: RedisChannelLayer.__init__() got an unexpected keyword argument 'ssl_cert_reqs'```.

because the CHANNELS_LAYER CONFIG was like this
```"BACKEND": "channels_redis.core.RedisChannelLayer"```

I had to uninstall the channels redis, ``channels-redis``, and install  ``channels_redis`` for it work. And use your configuration as below:

```CHANNEL_LAYERS = {
   "default": {
    "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
    "CONFIG": {
        "hosts":[{
            "address": "rediss://:your_redis_url",  # "REDIS_TLS_URL"
            "ssl_cert_reqs": None,
        }]
    }
}
}```